### ISSUE TITLE
Clarify API status with methods that modify receiver

### ISSUE THREAD

**Issue by ronan-gloo** [objective-php/primitives#1]
For methods that modify the internal state of primitive objects, we must decide if the returned value should be the current reference or a new instance.

In almost all languages where scalars are objects, operations are applied on a new instance, which is returned. We should stick to this behavior, and not consider such methods as kind of implicit mutators.
This is a common accepted (and expected) behavior.

In Ruby:

``` ruby
str = "Hello World";
str.downcase.hash == str.hash # False
```

Ruby has special "!" notation for methods that modify the receiver

In Javascript:

``` javascript
var str = "Hello World";
str.toUpperCase();

console.log(str); // "Hello World"
```

In Python:

``` python
str = 'Hello World';
id(str) == id(str.upper()) # False
```

---

In other hand, with some array functions, PHP works with references. For those particular cases, if they are implemented in Primitives,i think we must stick with the actual PHP implementation.
Void or boolean methods must be implemented with fluent interface in Primitives

Here some of them:
- `array_*sort`
- `array_*shift`
- `array_push`
- `array_pop`
- `array_walk`
- `shuffle`

As some of parts of the Array / Collection methods are shared with String (ie: shuffle), it may be reasonable to share this behavior in order to produce a consistent API.

**Comment by gauthier** [comment]
Ronan,

I fully agree! To tell the truth, I was wondering this point... at this stage, some methods amend the object base value, other don't but there is no clear rule to determine in which case methods should modify or not. Your proposal makes this choice consistent, and I like that ;)

That said, I'm still in favor of some `apply()`method expecting a callback that would allow to modify internal value without reassignation. 

So Instead of: 

``` php
// upper case name
$name = $name->upper();
```

We could write something like:

``` php
// upper case name
$name->apply(function($string) { return mb_strtoupper($string);});
```

Or even simpler, using interface defined `set()` method (assuming this method accepts an instance of the same class as value):

``` php
// upper case name
$name->set($name->upper());
```

**Comment by ronan-gloo** [comment]
I like the apply method, which appear much meaningful for all possible cases

``` php

// php function
$name->apply('mb_strtoupper');

// call object method and apply it ?
$name->apply('upper', true);

// primitive can implements __invoke method that return the internal value
$name->apply($name->upper());

// object callback
$name->apply([$name, 'upper']);

// Closure
$name->apply(function($string) { return mb_strtoupper($string);});
```

**Comment by gauthier** [comment]
Using __invoke to return value sounds interesting... but would also be redundant with the get() method defined in PrimitiveInterface. My guess is that the _invoke method maybe could be used for another base action implementation... but I don't which yet :)

By the way, I don't see any call to `__invoke()` in your example ;)

**Comment by gauthier** [comment]
`apply()` has been implemented ; I'll soon modify all existing methods so that they return clones instead of modifying internal values by default.

**Comment by gauthier** [comment]
@ronan-gloo I implemented the behaviour you suggested... while it did make sense on paper, I'm still wondering if this is actually the best way to go. I mean that most of the time, you'll need to actually work with your data, without any need for keeping the original one as is.

So I was thinking that instead of cloning the object any time you call a method likely to modify the internal value, you'd better to clone it whenever you actually need it.

Moreover, we could implement a `reset()` method allowing to revert the internal value to its internal state. That would be very lightweigth (in most cases), just copying the set value. The beahaviour would then look like this:

``` php

$string = new String('test');

echo $string->upper(); // 'TEST'
echo $string; // 'TEST'
$string->reset();
echo $string; // 'test'
```

If you actually need to keep both initial and amended value, you can do that:

``` php
$unitPrice = 11;
$quantity = 2;
$vat = 0.17;

$price = new Numeric($unitPrice);

$totalPrice = clone $price->multiplyBy($quantity);

$vat = clone $totalPrice->multiplyBy($vat);

echo 'Unit price: '  . $price . PHP_EOL;
echo 'Quantity:' . $quantity . PHP_EOL;
echo 'Total price:' . $totalPrice . PHP_EOL;
echo 'V.A.T.:' . $vat . PHP_EOL;

// Total price + VAT
echo 'Grand total:' . $totalPrice->add($vat) . PHP_EOL;

// Unit price unchanged
echo 'Unit price: '  . $price . PHP_EOL;
```

For this result:

```
Unit price: 11
Quantity:2
Total price:22
V.A.T.:3,74
Grand total:25,74
Unit price: 11
```

I think that this way to use object would be much more intuitive and comfortable.

**Comment by ronan-gloo** [comment]
@gauthier At first look, it does not seem's very intuitive to me, an not very fluent friendly. I'm sure that one of the keyword of that library should be "concise".
As first step, i think we can categorize API methods in order to help us.

Right now, i am able to distinct few "groups":

#### informational
- `length`
- `get`
- ...etc

#### transtype
- `split`
- `join`
- ..etc

#### search
- `indexOf`
- `contains`
- `match`
- ..etc

#### transform
- `upper`
- `lower`
- ...etc

#### operator replacement
- `multiplyBy`
- `divideBy`
- ...etc

For both first groups, problem is solved by itself.
Your second example illustrate how "operator replacement" methods should behave.
PHP operators allow us to work directly on variables, or store the result of the operation into a new one:

```
$result = 1 / 2;

// or
$result /= 2;
```

Your example can be translated with the second example.
Im wondering if we must supports, in some way, both logics ? If yes, what kind of "smart" markers we can find to make it self explanatory while reading code ?

About "search" and "transform" groups, i am still convinced that methods should return new objects.

**Comment by gauthier** [comment]
My point is that most of the time, we don't need to go back to initial value after it is transformed. I totally agree with the "concise", even "compact" keywords to describe the code I'd like to write using Objective PHP.

Actually I'm still thinking on that and have some other proposals to try to make both approach work together.

First let me translate/extend your example with my syntax proposal:

``` php

// first case: we want to apply a treatment on the value

// native way
$result = $result/2;
// or
$result /= 2;

// ObjectivePHP's way:
$result->divideBy(2);

// other case: we want to also keep $result

// native way:
$result2 = $result/2;

// ObjectivePHP's way:
$result2 = clone $result->divideBy(2); // $result is kept untouched thanks to clone high precedence
```

Now, let's imagine that you chose to apply your treatment, but finally need to get the initial value back. That could be handled easily:

``` php
$result->divideBy(2);
echo $result . ' is lower than ' . $result->getInitialValue();
```

Other way to get back to the initial value:

``` php
$result->divideBy(2);

echo $result . ' is the result of Numeric::divideBy(2) method applied on $result object';

// revert to initial value:
$result->reset();
echo 'It was applied on ' . $result;
```

Sincerely, I think that applying treatment by default for the `transform` methods family would allow in the same time to write a more compact code and also to save some memory (unless we choose to implement the 'rollback' feature described above) since object clones would be generated only when necessary.

Moreover, the library code itself would be much more easy to write (and read!), and less exposed to side effects if we keep the `clone` calls outside:

``` php
$name = $name->lower()->ucfirst(); 
// 2 clones generated + $name destruction + new memory allocation

// versus
$name->lower()->ucfirst(); 
// no clone generated ; no memory allocation for a new object ; only internal value update
```

And I have to say that I hate writing `$var = treatment($var)` :) I always preferred methods working on parameters using references rather than value!

**Comment by ronan-gloo** [comment]
Event if i think this is more a conceptual issue than a performance one, the simplest way to handle both cases is actually your proposal, and it will fit the the passing "object by reference" constraint when working with multiples methods on the same primitive object.

That said, `clone` keyword force us to use intermediate variables, we can also handle it internally with something like:

``` php
$localResult = $name->copy()->lower()->ucfirst();
```

And Btw, i definitely hate the reset() purpose :)

**Comment by gauthier** [comment]
I don't understand your point regarding `clone` forcing to use intermediate variables:

``` php
$localResult = $name->copy()->lower()->ucfirst();
$localResult = clone $name->lower()->ucfirst();
```

Both syntaxes look very close to me, except that the latter makes use of native language construct, and that's why I do prefer this one ;)

Now a good news: we totally agree on `reset()` being a "bad good idea" :) 

So may we agree on those points?
- the default behaviour of transformation methods will be to amend internal value
- `clone` would easily and efficiently allow the developers to copy objects in order to keep initial values untouched
- we won't bother keeping both initial and amended internal values (hopefully, this will save a lot of memory in huge iterating scripts!)

**Comment by ronan-gloo** [comment]
"the default behaviour of transformation methods will be to amend internal value"
Yes !

"clone would easily and efficiently allow the developers to copy objects in order to keep initial values untouched"

Not always, because clone operates once the whole chain has been evaluated. We must be able to clone the object at some desired point:

``` php
$str = new String('Hello');
$cloned = clone $str->lower()->upper();

$str = 'HELLO'
$cloned = 'HELLO'

// Not the same purpose as:
$str = new String('Hello');
$copied =  $str->copy()->lower()->upper();

$str = 'Hello'
$copied = 'HELLO'

```

"we won't bother keeping both initial and amended internal values (hopefully, this will save a lot of memory in huge iterating scripts!)"
Hoooooo... yes !!

**Comment by gauthier** [comment]
Hey, I think there is some misunderstanding with how clone works. As said before, this language construct is evaluated with a very high precedence, thus your example below is wrong:

``` php
$str = new String('Hello');
$cloned = clone $str->lower()->upper();

$str = 'HELLO'; // Wrong: $str is unchanged!!
$cloned = 'HELLO';
```

Because clone is evaluated prior to most other operators, this piece code could be describe as follow:

``` php
// $cloned = clone $str->lower()->upper();
//
// is equal to:
//
$cloned = clone $str;
$cloned->lower()->upper();
```

If you still in doubt, please test it ;) I played around with clone before proposing it, and to tell the truth I was not pretty sure it would act as expected, but it does!

**Comment by ronan-gloo** [comment]
http://3v4l.org/3fmVL

**Comment by gauthier** [comment]
My bad!!!!!!!!!!!!!!!!!!!!!!!!!!

I was testing pieces of code using the already modified version of the library, returning clones indeed :)

So you're right, clone doesn't do the job the way I'd like to. So a `copy()`, or even `clone()`;) method would be quite useful!

**Comment by gauthier** [comment]
So, I'm still thinking on this issue. 

I'm not very confortable with the `copy()` ; even if at this point, this is still the best solution we agreed on ;)

Now, what's missing to PHP to achieve what I'd like to do is construction for `clone`that would be similar to `new`:

``` php
// while you can do that:
$name = (new String)->lower();

// you can't do:
$transformedName = (clone $name)->upper();
```

To work around this language missing feature, a trivial function, acting as a kind of precedence enforcer could do the trick:

``` php
<?php


class String
{

    protected $value;

    public function __construct($string)
    {
        $this->value = $string;
    }

    public function lower()
    {
        $this->value = strtolower($this->value);

        return $this;
    }

    public function upper()
    {
        $this->value = strtoupper($this->value);

        return $this;
    }

    public function __toString()
    {
        return $this->value;
    }
}

function with($expr)
{
    return $expr;
}

$name = new String('Php');

echo 'Name was: ' . $name . PHP_EOL;

$name->upper();

with($clonedName = clone $name)->lower();

echo 'Cloned name is: ' .  $clonedName . PHP_EOL;

echo 'Name now is: ' . $name . PHP_EOL;
```

I'm pretty sure I would do that myself :) Now the question is: should we encourage such a practice?

Thus, should we integrate this function in the ObjectivePHP namespace? 

If think that this trick could be useful for preventing developers from creating intermediate variables.

By the way, `with()` is probably the best name for this pseudo language construct, but it's good enough to illustrate the idea.

**Comment by gauthier** [comment]
Another thing... under some circumstances, it is quite meaningful to implement to different methods depending on your will to amend or not the internal value.

I just implemented a `crop()` method, more or less identical to `extract()` ; but the first one actually modifies the internal value while the latter returns a new String (which sounds consistent with its name ;)) :

``` php

$string = new String('_underscore');
$cleaned = $string->extract(1); 
// (string) $cleaned == 'underscore' 
// (string) $string == '_underscore' 

$string->crop(1);
// (string) $string == 'underscore' 
```

NOTA: the overall behaviour of both methods is the same as substr() native function
